### ISSUE TITLE
Unable to run s6-supervise

### ISSUE THREAD

**Issue by oblomovx** [youegraillot/lidarr-on-steroids#20]
When I run the container with the docker-compose script, I get the following error.

s6-supervise setup (child): fatal: unable to exec run: Permission denied

and Deemix is not started.

I'm running docker on Windows

**Comment by youegraillot** [comment]
Are you using the docker compose from the repository or from the README ?

**Comment by oblomovx** [comment]
From the README

I tried the one from the repository and got:

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount732990062/Dockerfile: no such file or directory

**Comment by youegraillot** [comment]
Ah, it seems that you have a special docker setup when launching my compose
Can you explain how you're launching this ? Does other `docker compose` commands work ?

**Comment by youegraillot** [comment]
For the first issue, it seems that it is related to your docker installation : https://github.com/linuxserver/docker-sonarr/issues/28

For the second one (with the compose from the repos), the build error is due to your usage of buildkit, I renamed the file to hopefully fix that : https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0

**Comment by youegraillot** [comment]
I pushed a workaround from https://github.com/linuxserver/docker-sonarr/issues/28

Does this fix your issue ?

**Comment by youegraillot** [comment]
Fixed with 0fd770c8fed6c8210a7eced182d1d51b289526d2

**Comment by oblomovx** [comment]
Thanks, it is working now!
