### ISSUE TITLE
Deemix works as download client but not indexer

### ISSUE THREAD

**Issue by nchanson93** [youegraillot/lidarr-on-steroids#22]
Hey, love this project but recently had an issue where Deemix no longer works as an indexer. Have wiped the container/volume and started from scratch but the issue persists. Compose script and log attached.

[docker-compose.txt](https://github.com/youegraillot/lidarr-on-steroids/files/10182097/docker-compose.txt)
[logs.txt](https://github.com/youegraillot/lidarr-on-steroids/files/10182099/logs.txt)

**Comment by youegraillot** [comment]
Please be more specific on your issue.

What do you mean by 'Deemix works as download client but not indexer' ?
What image version do you use ?

Also, the error I'm seeing in you logs :
`Failed to bind to address http://[::]:8686: address already in use.`
was fixed by https://github.com/youegraillot/lidarr-on-steroids/issues/21, which should restart you container on plugin install/update, if not I encourage you to update to the latest version and restart

**Comment by nchanson93** [comment]
I wish I could be more specific, Deemix is autoconfigured as a download client but not as an indexer. When trying to add it manually nothing really happens and the logs don't seem to be very helpful.

**Comment by youegraillot** [comment]
Ok, so the autoconfigure part is adding Deemix in Lidarr UI correctly in the indexer section after you've entered your credentials into Deemix, but not into the downloader section

Did you try setting the lastest version in your compose (1.2.7) and restart ?

**Comment by dolichomps** [comment]
i am having the same issue on 1.2.7, including `Failed to bind to address http://[::]:8686: address already in use.` which appears after restating lidarr from the web ui

**Comment by youegraillot** [comment]
> i am having the same issue on 1.2.7, including `Failed to bind to address http://[::]:8686: address already in use.` which appears after restarting lidarr from the web ui

Please open an other issue if you're still experimenting this
You should not restart lidarr from the web-ui but restart the container entirely because the plugin system needs a full restart
