### ISSUE TITLE
Lidarr not updating

### ISSUE THREAD

**Issue by janaxhell** [youegraillot/lidarr-on-steroids#41]
**Describe the bug**
LOS keeps saying it could not update, but it can be done from docker, but from docker it just pulls the same build. Info says it's based on hotio, which is constantly updated, what is happening? Is this project still maintained?

**Comment by youegraillot** [comment]
I just updated the image

LOS does not autoupdate
The main focus is stability, and because the plugins feature is still experimental I think it's best that I manually check updates so we don't end up with a broken image

I will enable it for the base image of Lidarr in the future when the plugins PR is merged
